pipeline {
    agent {
        kubernetes {
            yamlFile 'jenkins/podTemplate.yaml'
            defaultContainer 'docker'
        }
    }

    options {
        ansiColor('xterm')
    }

    stages {
               
        stage('Latest') {
            steps {
                sh 'docker build -t registry.anthonyoteri.com/docker-yarn:latest -f Dockerfile .'
            }

            post {
                success {
                    sh "docker push registry.anthonyoteri.com/docker-yarn:latest"
                }
            }
        }

        stage('Slim') {
            steps {
                sh 'docker build -t registry.anthonyoteri.com/docker-yarn:slim -f Dockerfile.slim .'
            }
            post {
                success {
                    sh "docker push registry.anthonyoteri.com/docker-yarn:slim"
                }
            }
        }
    }
}
