pipeline {
    agent {
        kubernetes {
            yamlFile 'jenkins/podTemplate.yaml'
            defaultContainer 'docker'
        }
    }

    options {
        ansiColor('xterm')
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/anthonyoteri/docker-yarn'
            }
        }
       
        stage('Build') {
	    steps {
	        sh 'docker build -t registry.anthonyoteri.com/docker-yarn:latest -f Dockerfile .'
            sh 'docker build -t registry.anthonyoteri.com/docker-yarn:slim -f Dockerfile.slim .'
            }
	}
    }

    post {
        success {
	    sh "docker push registry.anthonyoteri.com/docker-yarn:latest"
        sh "docker push registry.anthonyoteri.com/docker-yarn:slim"
        }
    }
}
